sudo: required

language: python

python:
  - "2.7"
  - "3.5"

before_install:
  - git clone -q --branch=master https://github.com/Itseez/opencv.git opencv
  - python find_version.py > tmp 
  - opencv_version=$(cat tmp)
  - rm tmp
  - echo $opencv_version

install: 
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then sudo apt-get install python2.7-dev; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then sudo apt-get install python3.5-dev; fi
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - cd opencv
  - mkdir build
  - whereis python
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then cmake -H"." -B"build" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_opencv_python3=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DPYTHON2_EXECUTABLE=${VIRTUAL_ENV}/bin/python -DPYTHON2_LIBRARY=/usr/lib/libpython2.7mu.so -DPYTHON2_INCLUDE_DIR=/usr/include/python2.7m -DPYTHON2_PACKAGES_PATH=${VIRTUAL_ENV}/lib/python2.7/site-packages -Wno-dev; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then cmake -H"." -B"build" -DCMAKE_BUILD_TYPE=RELEASE -DBUILD_opencv_python2=OFF -DBUILD_SHARED_LIBS=OFF -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DPYTHON3_EXECUTABLE=${VIRTUAL_ENV}/bin/python -DPYTHON3_LIBRARY=/usr/lib/libpython3.5mu.so -DPYTHON3_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON3_PACKAGES_PATH=${VIRTUAL_ENV}/lib/python3.5/site-packages -Wno-dev; fi
  - cd build 
  - cmake --build . --config Release
  - cd ../..
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then cp opencv\build\lib\RELEASE\*.pyd opencv-python/cv2; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then cp opencv\build\lib\python3\Release\*.pyd opencv-python/cv2; fi
  - python setup.py bdist_wheel --opencv-version "$opencv_version-$TRAVIS_BUILD_NUMBER"

before_script:
  - pip install --no-index --find-links=opencv-python\dist\ opencv-python

script:
  - cd tests
  - python -m unittest test
